services:
  postgres:
    image: postgres:15
    container_name: secunda_test
    environment:
      POSTGRES_DB: organizations_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  backend:
    build: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/organizations_db
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge